name: LockDown
main: me.zack6849.MaintenanceMode.MaintenanceMode
version: 1.5.3
author: zack6849
commands:
    ld:
      description: LockDown Toggle
      usage: /ld <arguments> 
      permission: ld.toggle
      permission-message: You don't have <permission>
permissions:
    ld.toggle:
        description : permission to toggle LockDown.
    ld.bypass:
        description: permission to join during LockDown.