name: MaintenanceMode
main: me.zack6849.MaintenanceMode.MaintenanceMode
version: 1.4
commands:
    mm:
      description: MaintainenceMode Toggle
      usage: /mm <arguments> 
      permission: mm.toggle
      permission-message: You don't have <permission>
permissions:
    mm.toggle:
        description : permission to toggle Maintainence Mode
    mm.bypass:
        description: permission to join during MaintenenceMode.